### ISSUE TITLE
Bug -  RAMLDataOject >> RAMLDataObject 

### ISSUE THREAD

**Issue by marcosborges** [mikestowe/php-raml2html#3]
Congratulations on your script. He's helping me a lot .

I'm using it and detected a bug and would like to share it with you.

In ramlDataObject.php file at line 68:

[ FROM]
$ t = new RAMLDataOject ( spyc_load_file ( $ matches [ 1] ) ) ;

[TO ]
$ t = new RAMLDataObject ( spyc_load_file ( $ matches [ 1] ) ) ;

only lacked the RAMLDataO b "b" ject .

I hope to have helped.

**Comment by mikestowe** [comment]
Thanks marcosborges!  This has been fixed now :)
